import { createTour } from "../Utils/TournamentData";
import { GenIntCaracters } from "../Utils/Cryptography";

export const SchedulerTour = async () =>
{
      await createTour({
          id: GenIntCaracters(12),
          type: 1,
          status: 0,
          tournamentDate: new Date('2026-07-03T22:00:00.000Z'),
          startHour: 22,
          startMinute: 0,
          invitationOffsetHours: 0,
          invitationOffsetMinutes: -10,
          registrationOffsetHours: 0,
          registrationOffsetMinutes: -10,
          invitationCloseOffsetHours: 0,
          invitationCloseOffsetMinutes: 0,
          tournamentName: "zn 1v1 bd only punch",
          maxInvites: 2,
          partySize: 1,
          currentInvites: 0,
          phaseCount: 1,
          roundCount: 4,
          themeColor: "#1156d6f5",
          entryFeeAmount: 1,
          prizeAmount: 500,
          sponsorName: "SA",
          sponsorImageUrl: "",
          imageUrl: null,
          iconUrl: "https://cdn.discordapp.com/avatars/1383168367858286724/50a83305d8b5e1f648892d8ad5888c2d.png?size=2048",
          highlightsUrl: "https://discord.gg/sgboxer",
          streamUrl: "https://discord.gg/sgboxer",
          serverRegion: "SA",
          entryFeeType: 10,
          entryFeeId: "1019395748292202883",
          entryFeeItemAmount: 1000,
          disableEmotes: "6,8,124,13,123,55,122,156,174,217,218,234,239,240,254",
          phaseOverrideLevel: "level19_block",
          requiredVersion: "0.56",
          minimumVersion: "0.56",
          overrideMaxQualified: "1",
          maxWaitTime: "30",
          gameRoundCount: "1",
          phaseType: 1,
          maxPlayers: 2,
          maxTeams: 2,
          minTeamsPerMatch: 2,
          maxTeamsPerMatch: 2,
          minCheckinsPerTeam: 1,
          groupCount: 1,
          isLoserBracketSeeded: true,
          isSkipAllowed: false,
          maxLoses: 1,
          allowedRebuyCount: 0,
          allowedRebuyUntilRoundId: 0,
          rebuyPrice: 0,
          roundMaxLength: 12,
          roundMinGameLength: 8,
          winScore: "1",
          matchPointDistribution: "1",
          prizeToPlace: 1000,
          prizeType: 500000,
          prizeId: 1,
          onlyInviteds: true,
          Convidados: ["0", "1", "98", "6546", "9171"]
        });
}